### ISSUE TITLE
Implementar un algoritmo genetico para solucionar le problema del BPP-2D.

### ISSUE THREAD

**Issue by harpomaxx** [DiegoCC14/DiegoCazon_ProyectoFinal_IA1#10]
Implementar un algoritmo genético de acuerdo a las especificaciones planteadas en este [documento](https://github.com/DiegoCC14/DiegoCazon_ProyectoFinal_IA1/blob/master/Estructuras%20y%20Metodos%20a%20Usar/Propuesta_GA.pdf)

**Comment by DiegoCC14** [comment]
se pudo aplicar algoritmos geneticos para resolver el problema de cumulo de particulas, se encuentra con el nombre de <a href="https://github.com/DiegoCC14/DiegoCazon_ProyectoFinal_IA1/blob/master/Geneticos.py" > Geneticos.py</a>
