### ISSUE TITLE
generar un conjunto de prueba para evaluar las propuestas desarolladas.

### ISSUE THREAD

**Issue by harpomaxx** [DiegoCC14/DiegoCazon_ProyectoFinal_IA1#11]
Se trata de desarrollar un conjunto de casos de pruebas  de manera pseudo aleatoria y guardarlos para poder evaluar las diferentes propuestas desarrolladas durante el proyecto.

Por ejemplo podria ser algo asi como:

**Escenario 1.**  
- Contenedor de superficie 100x100. 
- Superficie maxima de una caja 10x10 (Esto significa que pueden haber cajas de cualquier tamaño mientras su superficie no sea superior a 100 (10x10)) 
- Numero máximo de cajas generadas 100

**Escenario 2:**
- Contenedor de superficie 100x100. 
- Superficie maxima de una caja 50x50 (Esto significa que pueden haber cajas de cualquier tamaño mientras su superficie no sea superior a 2500 (50x50)) 
- Numero máximo de cajas generadas 100

**Escenario 3:**
- Contenedor de superficie 100x100. 
- Superficie maxima de una caja 3x3 (Esto significa que pueden haber cajas de cualquier tamaño mientras su superficie no sea superior a 9 (3x3)) 
- Numero máximo de cajas generadas 100

Se deberan generar 30 casos para cada uno de los escenarios y guardarlos en archivos independientes.

**I M P O R T A N T E**
LOS CASOS SON A MODO DE EJEMPLOS, Se deberian investigar los distintos tipos de escenarios mas comunes (dificiles y faciles) para poder evaluar el algoritmo

**Comment by DiegoCC14** [comment]
<a href="https://github.com/DiegoCC14/DiegoCazon_ProyectoFinal_IA1/blob/master/Cajas.py">Cajas.py</a> genera las cajas aleatoriamente y haciendonos saber que existe un orden perfector donde las cajas encajan sin dejas espacios, no genera casos reales ya que en la vida real nosotros no sabemos que tal orden deja menos espacios, entonces con Cajas.py esto si lo sabemos, existe un orden perfecto y que tanto nuestro algoritmo se hacereca a este.

**Comment by DiegoCC14** [comment]
esto lo hice porque encontre un caso de cajas en donde era imposible ordenarlas bien, entonces el algoritmo me daba malos resultados, con este metodo, se que existe un orden perfecto sin espacion vacios, entonces puedo ver cuanto espacio sin usar obtengo
![imagen](https://user-images.githubusercontent.com/63387396/163662203-d2593cf5-5618-4480-ace5-b9c4d396680f.png)
- En este caso tengo un contenedor de area 25, y cajas en las cuales la suma de las areas es igual a 25, pero si tratamos de ordenarlas terminamos dejamos una caja de 2x2 que es imposible ingresar, entonces todos los resultados que el algoritmo me arrojaria serian desde 4 de area desperdiciada para arriba, esto para un caso simple.

**Comment by DiegoCC14** [comment]
<a href="https://github.com/DiegoCC14/DiegoCazon_ProyectoFinal_IA1/blob/master/Cajas.py">Cajas.py</a> Genera cajas que se pueden acomodar en el contenedor sin dejar espacios:
- Definimos solo el ancho del contenedor y definimos la cantidad de niveles que ingresaremos.
- Cada Nivel contiene cajas de igual dimencion, la altura de las cajas sera un numero aleatorio y la anchura es la divicion de un numero par desde 2 a 10, esto puede dejar espacios y con esos espacios restantes generamos otra caja de misma altura y ancho igual al espacio restante.
- Si ingresamos 10 niveles, entonces se generaran 10 grupos de cajas, entonces el contenedor final tendra, tendra una anchura definida, pero la altura dependera de la altura de los niveles, de esta forma existe una forma de llenar el contenedor sin dejar espacios 
![imagen](https://user-images.githubusercontent.com/63387396/163682982-f831b4e2-9eb4-4a3c-b295-85b4474bee5b.png)
