### ISSUE TITLE
RENOMBRAR LA CARPETA /Articulos para el desarrollo/ 

### ISSUE THREAD

**Issue by harpomaxx** [DiegoCC14/DiegoCazon_ProyectoFinal_IA1#5]
Si lo que vas a poner ahi es bibliografia y articulos/documentos que plantean soluciones posibles a tu problema. Entonces cambiar el nombre de dicha carpeta por `Bibliografia`

**Comment by DiegoCC14** [comment]
Se cambio Articulos para el Desarrollo a Bibliografia.
