### ISSUE TITLE
Acortar nombres de los articulos de /Articulos para el desarrollo/

### ISSUE THREAD

**Issue by harpomaxx** [DiegoCC14/DiegoCazon_ProyectoFinal_IA1#6]
Los nombres son muy largos y se dificulta la lectura. 
Si son articulos con autor, colocar un nombre como **_Toro2007.pdf_** (ejemplo para el caso de: _**EMPAQUETAMIENTO RECTANGULAR BIDIMENSIONAL TIPO GUILLOTINA CON ALGORITMOS GENETICOS.pdf**_)

**Comment by DiegoCC14** [comment]
Se acortaron los nombres de los documentos de Blibliografia

**Comment by harpomaxx** [comment]
pero no se respetó el enfoque propuesto. Por ejemplo tenes varios papers. Uno de enrique alba por ejemplo. Otro de Toro. La idea es que esos articulos sean renombramos a `Toro2007`, Alba200 y martinez 2006(por ejemplo, no es se si los años sean correctos) 

Eventualmente si queres tener una descripcion podes crear  un archivo README.md con los nombres de los articulos, autores y un link a pdf.

**Comment by DiegoCC14** [comment]
Se acortaron los nobres Algoritmo_Autor_anio
