### ISSUE TITLE
Acortar los nombres de los documentos dentro de Estructuras y Metodos a Usar/

### ISSUE THREAD

**Issue by harpomaxx** [DiegoCC14/DiegoCazon_ProyectoFinal_IA1#7]
Los nombres son muy largos cambiar por nombres descriptivos y cortos:
ejemplos:
1. PropuestaPSO.pdf
2. PropuestaGA.pdf
3. PropuestaXX.pdf

**Comment by DiegoCC14** [comment]
Ya se acortaron los nombre a Propuesta_XX.pdf

**Comment by harpomaxx** [comment]
siguen habiendo nombres Largos. Fijate de achicar el nombre del documento sobre arbol guillotina

**Comment by DiegoCC14** [comment]
se redujo el nombre de los archivos de Estructuras y Metodos a Usar
